bootstrap_for_dummies/flask_dash/routes.py
import functools
import os
from flask import Blueprint
from flask import flash
from flask import request
from flask import Flask, url_for, render_template, redirect
from jinja2 import Template
from .db import get_engine
from .auth import login_required
from .forms import SearchForm
from  . import queries
import pandas as pd
from flask import g

bp = Blueprint("routes", __name__)


@bp.route("/bye")
def bye():
    tm = Template(""" Bye!""")
    return tm.render()


@bp.route("/")
def hello():

    return render_template('iframe_test.html')



@bp.route("/search", methods=['GET', 'POST'])
@login_required
def search():
    form = SearchForm(request.form)
    if request.method == "POST" and form.validate():
        if not form.author.data and not form.year.data and not form.topic.data:
            flash("Some fields must be filled.")
        else:
            return redirect(url_for('routes.articles', year=form.year.data, author=form.author.data, topic=form.topic.data))

    return render_template("search/search.html")



@bp.route("/articles")
@login_required
def articles():
    d = request.args.to_dict()
    year = d.get('year', None)
    author = d.get('author', None)
    topic = d.get('topic', None)

    db = get_engine()
    if author:
        df1 = pd.read_sql_query(
            queries.q_authors_articles,
            con=db,
            params={'authorname': '%' + author + '%'},
            index_col='_id'
        )

        if year:
            df1 = df1[df1.year == int(year)]
        if topic:
            df1 = df1[df1.topics.str.contains(topic)]
    else:
        if year:
            df1 = pd.read_sql_query(
                queries.q_year_articles,
                con=db,
                params={'year': year},
                index_col='_id'
            )
            if topic:
                df1 = df1[df1.topics.str.contains(topic)]
        else:
            df1 = pd.read_sql_query(
                queries.q_topic_articles,
                con=db,
                params={'topic': '%' + topic + '%'},
                index_col='_id'
            )

    df1['author_names'] = df1['author_names'].map(lambda x: x.split('; '))
    df1['topics'] = df1['topics'].map(
        lambda x: x.strip('{}').split(',') if isinstance(x, str) else [])

    df_likes = pd.read_sql_query(
        queries.q_user_likes,
        con=db,
        params={'userid': g.user["id"]}
    )

    df1['liked'] = 0
    articles_ = set(df1.index.to_list())

    df1.loc[[x for x in df_likes.article_id.to_list() if x in articles_], 'liked'] = 1

    return render_template("search/sometable_view.html", user_id=g.user["id"], article_list=df1.reset_index(names=['_id']).to_dict('records'))



@bp.route("/one_article")
@login_required
def one_article():
    d = request.args.to_dict()
    _id = d.get('art_id', None)

    db = get_engine()

    df1 = pd.read_sql_query(
        queries.q_1article,
        con=db,
        params={'article_id': _id},
        index_col='_id'
    )
    if len(df1) == 0:
        return render_template("search/article_not_found.html")

    df1['author_names'] = df1['author_names'].map(lambda x: x.split('; '))
    df1['references'] = df1['references'].map(lambda x: x.split('; '))
    df1['topics'] = df1['topics'].map(lambda x: x.strip('{}').split(','))

    df_likes = pd.read_sql_query(
        queries.q_user_article_like,
        con=db,
        params={'userid': g.user["id"], 'article_id': _id}
    )
    if len(df_likes):
        df1['liked'] = 1
    else:
        df1['liked'] = 0

    return render_template("search/article_view.html", user_id=g.user["id"], article_obj=df1.reset_index(names=['_id']).to_dict('records')[0])


@bp.route("/top_authors")
def top_authors():

    db = get_engine()

    df1 = pd.read_sql_query(
        queries.q_top_authors,
        con=db,
    )
    df1['years'] = df1['min_year'] + '-' + df1['max_year']
    df1.loc[df1[df1.min_year == df1.max_year].index, 'years'] = df1.loc[df1[df1.min_year == df1.max_year].index, 'min_year']
    return render_template("search/authors.html", authors_list=df1.to_dict('records'))


@bp.route("/cytoscape")
@login_required
def cytoscape():
    # d = request.args.to_dict()
    # topic = d.get('topic', None)
    # if not topic:
    #     flash("No topic specified.")
    #     redirect(url_for('top_authors'))
    #
    db = get_engine()
    # db.execute(queries.q_cytograph1)
    # df1 = pd.read_sql_query(
    #     queries.q_cytograph2,
    #     con=db,
    #     params={'topic': '%' + topic + '%'},
    # )
    #
    # return render_template(
    #     "/graph/graph.html",
    #     elmnt_list=df1.a1.map(lambda x: {'data': {'id': x}}).to_list()
    #                + df1[['_id', 'a1', 'a2']].apply(lambda row: {'data': {'id': row._id, 'source': row.a1, 'target': row.a2}}, axis=1).to_list()
    # )
    #
    # input_dir = r'F:\study\MADE\MADE22\project\dataset\normalized'
    # input_dir2 = r'F:\study\MADE\MADE22\project\dataset\connec_compont'
    #
    # aa_inter = pd.read_csv(os.path.join(input_dir, 'aa_inter.csv'))
    #
    #
    # articles_less = pd.read_csv(os.path.join(input_dir2, 'small_components_ids.csv'))
    #
    # df = aa_inter[['_id', 'author__id']].merge(aa_inter[['_id', 'author__id']], left_on='_id', right_on='_id',
    #                                            suffixes=['_1', '_2'])
    #
    # df = articles_less.merge(df, left_on='_id', right_on='_id')
                                               #                                            suffixes=['_1', '_2'])
    # df = df[df['author__id_1'] < df['author__id_2']]
    # df = df[df['author__id_1'].notna() & df['author__id_2'].notna()]
    # df.drop_duplicates(inplace=True)

    # return render_template(
    #     "/graph/graph.html",
    #     elmnt_list=list(
    #         map(lambda x: {'data': {'id': x}}, (set(df.author__id_1.to_list() + df.author__id_2.to_list()))))
    #                + df[['_id', 'author__id_1', 'author__id_2']].apply(
    #         lambda row: {'data': {'id': row._id, 'source': row.author__id_1, 'target': row.author__id_2}},
    #         axis=1).to_list()
    # )
    #------------------------------------------------------------------------------
    # aa_inter = pd.read_sql_query(
    #     queries.q_cytograph5,
    #     con=db
    # )
    # df = aa_inter[['_id', 'aa']].merge(aa_inter[['_id', 'aa']], left_on='_id', right_on='_id',suffixes=['_1', '_2'])
    # df = df[df['aa_1'] < df['aa_2']]
    # df = df[df['aa_1'].notna() & df['aa_2'].notna()]
    # df.drop_duplicates(inplace=True)
    #
    # return render_template(
    #            "/graph/graph.html",
    #            elmnt_list=list(map(lambda x: {'data': {'id': x}}, (set(df.aa_1.to_list() + df.aa_2.to_list()))))
    #                       + df[['_id', 'aa_1', 'aa_2']].apply(lambda row: {'data': {'id': row._id, 'source': row.aa_1, 'target': row.aa_2}}, axis=1).to_list()
    #        )
    # ------------------------------------------------------------------------------
    db.execute(queries.q_cytograph6)
    df = pd.read_sql_query(
        queries.q_cytograph7,
        con=db
    )
    input_dir2 = r'F:\study\MADE\MADE22\project\dataset\connec_compont'
    articles_less = pd.read_csv(os.path.join(input_dir2, 'small_components_ids.csv'))
    df = articles_less.merge(df, left_on='_id', right_on='_id')
    df = df[df['aa_1'].notna() & df['aa_2'].notna()]
    df.drop_duplicates(inplace=True)

    return render_template(
        "/graph/graph.html",
        elmnt_list=list(map(lambda x: {'data': {'id': x}}, (set(df.aa_1.to_list() + df.aa_2.to_list()))))
                   + df[['_id', 'aa_1', 'aa_2']].apply(
            lambda row: {'data': {'id': row._id, 'source': row.aa_1, 'target': row.aa_2}}, axis=1).to_list()
    )

@bp.route("/ldavis")
@login_required
def ldavis():
    return render_template('vis.html')

bootstrap_for_dummies/flask_dash/templates/search/article_not_found.html
{% extends 'base.html' %}
{% block content%}


<div class="article-container">
    Article not available.

</div>

</div>
{% endblock %}

{% block custom_scripts %}
<script src="{{ url_for('static', filename='js/socket.io.min.js') }}"></script>
<script>
    console.log("here we are");
    var hostpath = "http://127.0.0.1:5000";

    var path_2_heart_on="url(" + hostpath+"{{ url_for('static', filename='bin/heart_on.png') }})";
    var path_2_heart_off="url(" + hostpath+"{{ url_for('static', filename='bin/heart_off.png') }})";
    var paths = {1: path_2_heart_on, 0: path_2_heart_off};
    console.log(paths);
    var article_obj1 = {{ article_obj|safe }};

    console.log(article_obj1);
    let sel = "#" + article_obj1._id;
    $(sel).css('background-image', paths[article_obj1.liked]);

    var user_id = {{ user_id|safe }};
    console.log(article_obj1);

</script>
<script src="{{url_for('static', filename='/js/article.js')}}"></script>
{% endblock %}

bootstrap_for_dummies/flask_dash/templates/search/article_view.html
{% extends 'base.html' %}
{% block content%}


<div class="article-container">
    <div class="roww roww-title">
            {{ article_obj.title }}
        </div>
    <div class="roww roww-authors-tags">
        <div class="roww art-year">
            <p>{{ article_obj.year }} </p>
        </div>
        <div class="roww roww-art-authors">
            {% for author_name in article_obj.author_names %}
            <a href="{{ url_for('routes.articles', author=author_name) }}">{{ author_name }}</a>
            {% endfor %}
        </div>
        <div class="roww roww art-topics">
            {% for topic in article_obj.topics %}
            <a href="{{ url_for('routes.articles', topic=topic) }}">{{ topic }}</a>
            {% endfor %}
        </div>
    </div>

    <div class="roww roww-text">
        <p>Abstract</p>
        <div class="roww textt" >
            {{ article_obj.abstract }}
        </div>
    </div>
    <div class="roww ref-cit">
        <div class="roww citation" >
            <p> Cited: {{ article_obj.n_citation }} </p>
        </div>
        <div class="roww references" >
            {% for ref in article_obj.references %}
            <a href="{{ url_for('routes.one_article', _id=ref) }}">{{ ref }}</a>
            {% endfor %}
        </div>
    </div>
    <div class="like" id="{{ article_obj._id }}">

    </div>

</div>

</div>
{% endblock %}

{% block custom_scripts %}
<script src="{{ url_for('static', filename='js/socket.io.min.js') }}"></script>
<script>
    console.log("here we are");
    var hostpath = "http://127.0.0.1:5000";

    var path_2_heart_on="url(" + hostpath+"{{ url_for('static', filename='bin/heart_on.png') }})";
    var path_2_heart_off="url(" + hostpath+"{{ url_for('static', filename='bin/heart_off.png') }})";
    var paths = {1: path_2_heart_on, 0: path_2_heart_off};
    console.log(paths);
    var article_obj1 = {{ article_obj|safe }};

    console.log(article_obj1);
    let sel = "#" + article_obj1._id;
    $(sel).css('background-image', paths[article_obj1.liked]);

    var user_id = {{ user_id|safe }};
    console.log(article_obj1);

</script>
<script src="{{url_for('static', filename='/js/article.js')}}"></script>
{% endblock %}

bootstrap_for_dummies/flask_dash/templates/search/authors.html
{% extends 'base.html' %}
{% block content%}

<!-- name | sum(n_citation) | years active-->

<div class="table-container">

    <div class="row">
    <div class="col-md-6 auth-name">
        <p>Name</p>
    </div>
    <div class="col-md-1 auth-cited">
        <p>Cited</p>
    </div>
    <div class="col-md-2 auth-years">
        <p>Years</p>
    </div>

</div>
{% for author in authors_list %}

<div class="row">
    <div class="col-md-6 auth-name">
        <a href="{{ url_for('routes.articles', author=author.name) }}">{{ author.name }}</a>
    </div>
    <div class="col-md-1 auth-cited">
        <p> {{ author.citations }}</p>
    </div>
    <div class="col-md-2 auth-years">
        <p> {{ author.years }} </p>
    </div>

</div>
{% endfor %}
</div>
{% endblock %}

{% block custom_scripts %}
<script src="{{ url_for('static', filename='js/socket.io.min.js') }}"></script>

{% endblock %}

bootstrap_for_dummies/flask_dash/templates/search/results.html
{% extends 'base.html' %}
{% block content%}
<h1>Hello</h1>
        <div>
                {% for table in tables %}
                            {{titles[loop.index]}}
                            {{ table|safe }}
                {% endfor %}
        </div>
{% endblock %}

bootstrap_for_dummies/flask_dash/templates/search/search.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Search{% endblock %}</h1>
{% endblock %}

{% block content %}
<div class="">
  <form method="post">

    <label class="year_l" for="year">Year</label>
    <input class="year_f" name="year" id="year">

    <label class="auth_l" for="author">Author</label>
    <input class="auth_f" name="author" id="author">
    <hr>
    <label class="topic_l" for="topic">Topic</label>
    <input class="topic_f" name="topic" id="topic">

    <input class="submit" type="submit" value="Search">
  </form>
</div>
{% endblock %}

bootstrap_for_dummies/flask_dash/templates/search/sometable_view.html
{% extends 'base.html' %}
{% block content%}

<!-- article .id  .title .author .text .year-->

<div class="table-container">

    <div class="row">
    <div class="col-md-2 art-title">
        <p>Title</p>
    </div>
    <div class="col-md-6 art-topics">
        <p>Topics</p>
    </div>
    <div class="col-md-2 art-authors">
        <p>Authors</p>
    </div>
    <div class="col-md-1 art-year">
        <p>Year</p>
    </div>
    <div class="col-md-1">

    </div>
</div>
{% for article in article_list %}

<div class="row">
    <div class="col-md-2 art-title">
        <a href="{{ url_for('routes.one_article', art_id=article._id) }}">{{ article.title }}</a>
    </div>
    <div class="col-md-6 art-topics">
        {% for topic in article.topics %}
        <a href="{{ url_for('routes.articles', topic=topic) }}">{{ topic }}</a>
        {% endfor %}
    </div>
    <div class="col-md-2 art-author">
        {% for author_name in article.author_names %}
        <a href="{{ url_for('routes.articles', author=author_name) }}">{{ author_name }}</a>
        {% endfor %}
    </div>
    <div class="col-md-1 art-year">
        <p> {{ article.year }} </p>
    </div>
    <!--<div class="col-md-1 like" id="{{ article._id }}">
    </div> -->
    <!--
    <div class="col-md-1" id="{{ article._id }}" style="background-image:
    {{ url_for('static', filename='bin/heart_off.png') }};">
    </div>-->
    <div class="col-md-1 like" id="{{ article._id }}">
    <!--<img class="like" src="{{ url_for('static', filename='bin/heart_off.png') }}"/>-->
    </div>

</div>
{% endfor %}
</div>
{% endblock %}

{% block custom_scripts %}
<script src="{{ url_for('static', filename='js/socket.io.min.js') }}"></script>
<script>
    console.log("here we are");
    var hostpath = "http://127.0.0.1:5000";

    var path_2_heart_on="url(" + hostpath+"{{ url_for('static', filename='bin/heart_on.png') }})";
    var path_2_heart_off="url(" + hostpath+"{{ url_for('static', filename='bin/heart_off.png') }})";
    var paths = {1: path_2_heart_on, 0: path_2_heart_off};
    console.log(paths);
    var articles_list1 = {{ article_list|safe }};
    articles_list1.forEach((article1, i) => {
        console.log(article1);
        let sel = "#" + article1._id;
        $(sel).css('background-image', paths[article1.liked]);
    });
    var user_id = {{ user_id|safe }};
    console.log(articles_list1);

</script>
<script src="{{url_for('static', filename='/js/articles.js')}}"></script>
{% endblock %}