bootstrap_for_dummies/flask_dash/auth.py
import functools

from flask import Blueprint
from flask import flash
from flask import g
from flask import redirect
from flask import render_template
from flask import request
from flask import session
from flask import url_for
from werkzeug.security import check_password_hash
from werkzeug.security import generate_password_hash

from sqlalchemy.exc import IntegrityError

from .db import get_engine

bp = Blueprint("auth", __name__, url_prefix="/auth")


def login_required(view):
    """View decorator that redirects anonymous users to the login page."""

    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for("auth.login"))

        return view(**kwargs)

    return wrapped_view


@bp.before_app_request
def load_logged_in_user():
    """If a user id is stored in the session, load the user object from
    the database into ``g.user``."""
    user_id = session.get("user_id")

    if user_id is None:
        g.user = None
    else:
        g.user = (
            get_engine().execute("SELECT * FROM users WHERE id = %s", (user_id,)).fetchone()
        )


@bp.route("/register", methods=("GET", "POST"))
def register():
    """Register a new user.

    Validates that the username is not already taken. Hashes the
    password for security.
    """
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        db = get_engine()
        error = None

        if not username:
            error = "Username is required."
        elif not password:
            error = "Password is required."

        if error is None:
            try:
                db.execute(
                    "INSERT INTO users (username, password) VALUES (%s, %s)",
                    (username, generate_password_hash(password)),
                )
            except IntegrityError:
                # The username was already taken, which caused the
                # commit to fail. Show a validation error.
                error = f"User {username} is already registered."
            else:
                # Success, go to the login page.
                return redirect(url_for("auth.login"))

        flash(error)

    return render_template("auth/register.html")


@bp.route("/login", methods=("GET", "POST"))
def login():
    """Log in a registered user by adding the user id to the session."""
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        db = get_engine()
        error = None
        user = db.execute(
            "SELECT * FROM users WHERE username = %s", (username,)
        ).fetchone()

        if user is None:
            error = "Incorrect username."
        elif not check_password_hash(user["password"], password):
            error = "Incorrect password."

        if error is None:
            # store the user id in a new session and return to the index
            session.clear()
            session["user_id"] = user["id"]
            return redirect(url_for("index"))

        flash(error)

    return render_template("auth/login.html")


@bp.route("/logout")
def logout():
    """Clear the current session, including the stored user id."""
    session.clear()
    return redirect(url_for("index"))

bootstrap_for_dummies/flask_dash/routes.py
import functools
import os
from flask import Blueprint
from flask import flash
from flask import request
from flask import Flask, url_for, render_template, redirect
from jinja2 import Template
from .db import get_engine
from .auth import login_required
from .forms import SearchForm
from  . import queries
import pandas as pd
from flask import g

bp = Blueprint("routes", __name__)


@bp.route("/bye")
def bye():
    tm = Template(""" Bye!""")
    return tm.render()


@bp.route("/")
def hello():

    return render_template('iframe_test.html')



@bp.route("/search", methods=['GET', 'POST'])
@login_required
def search():
    form = SearchForm(request.form)
    if request.method == "POST" and form.validate():
        if not form.author.data and not form.year.data and not form.topic.data:
            flash("Some fields must be filled.")
        else:
            return redirect(url_for('routes.articles', year=form.year.data, author=form.author.data, topic=form.topic.data))

    return render_template("search/search.html")



@bp.route("/articles")
@login_required
def articles():
    d = request.args.to_dict()
    year = d.get('year', None)
    author = d.get('author', None)
    topic = d.get('topic', None)

    db = get_engine()
    if author:
        df1 = pd.read_sql_query(
            queries.q_authors_articles,
            con=db,
            params={'authorname': '%' + author + '%'},
            index_col='_id'
        )

        if year:
            df1 = df1[df1.year == int(year)]
        if topic:
            df1 = df1[df1.topics.str.contains(topic)]
    else:
        if year:
            df1 = pd.read_sql_query(
                queries.q_year_articles,
                con=db,
                params={'year': year},
                index_col='_id'
            )
            if topic:
                df1 = df1[df1.topics.str.contains(topic)]
        else:
            df1 = pd.read_sql_query(
                queries.q_topic_articles,
                con=db,
                params={'topic': '%' + topic + '%'},
                index_col='_id'
            )

    df1['author_names'] = df1['author_names'].map(lambda x: x.split('; '))
    df1['topics'] = df1['topics'].map(
        lambda x: x.strip('{}').split(',') if isinstance(x, str) else [])

    df_likes = pd.read_sql_query(
        queries.q_user_likes,
        con=db,
        params={'userid': g.user["id"]}
    )

    df1['liked'] = 0
    articles_ = set(df1.index.to_list())

    df1.loc[[x for x in df_likes.article_id.to_list() if x in articles_], 'liked'] = 1

    return render_template("search/sometable_view.html", user_id=g.user["id"], article_list=df1.reset_index(names=['_id']).to_dict('records'))



@bp.route("/one_article")
@login_required
def one_article():
    d = request.args.to_dict()
    _id = d.get('art_id', None)

    db = get_engine()

    df1 = pd.read_sql_query(
        queries.q_1article,
        con=db,
        params={'article_id': _id},
        index_col='_id'
    )
    if len(df1) == 0:
        return render_template("search/article_not_found.html")

    df1['author_names'] = df1['author_names'].map(lambda x: x.split('; '))
    df1['references'] = df1['references'].map(lambda x: x.split('; '))
    df1['topics'] = df1['topics'].map(lambda x: x.strip('{}').split(','))

    df_likes = pd.read_sql_query(
        queries.q_user_article_like,
        con=db,
        params={'userid': g.user["id"], 'article_id': _id}
    )
    if len(df_likes):
        df1['liked'] = 1
    else:
        df1['liked'] = 0

    return render_template("search/article_view.html", user_id=g.user["id"], article_obj=df1.reset_index(names=['_id']).to_dict('records')[0])


@bp.route("/top_authors")
def top_authors():

    db = get_engine()

    df1 = pd.read_sql_query(
        queries.q_top_authors,
        con=db,
    )
    df1['years'] = df1['min_year'] + '-' + df1['max_year']
    df1.loc[df1[df1.min_year == df1.max_year].index, 'years'] = df1.loc[df1[df1.min_year == df1.max_year].index, 'min_year']
    return render_template("search/authors.html", authors_list=df1.to_dict('records'))


@bp.route("/cytoscape")
@login_required
def cytoscape():
    # d = request.args.to_dict()
    # topic = d.get('topic', None)
    # if not topic:
    #     flash("No topic specified.")
    #     redirect(url_for('top_authors'))
    #
    db = get_engine()
    # db.execute(queries.q_cytograph1)
    # df1 = pd.read_sql_query(
    #     queries.q_cytograph2,
    #     con=db,
    #     params={'topic': '%' + topic + '%'},
    # )
    #
    # return render_template(
    #     "/graph/graph.html",
    #     elmnt_list=df1.a1.map(lambda x: {'data': {'id': x}}).to_list()
    #                + df1[['_id', 'a1', 'a2']].apply(lambda row: {'data': {'id': row._id, 'source': row.a1, 'target': row.a2}}, axis=1).to_list()
    # )
    #
    # input_dir = r'F:\study\MADE\MADE22\project\dataset\normalized'
    # input_dir2 = r'F:\study\MADE\MADE22\project\dataset\connec_compont'
    #
    # aa_inter = pd.read_csv(os.path.join(input_dir, 'aa_inter.csv'))
    #
    #
    # articles_less = pd.read_csv(os.path.join(input_dir2, 'small_components_ids.csv'))
    #
    # df = aa_inter[['_id', 'author__id']].merge(aa_inter[['_id', 'author__id']], left_on='_id', right_on='_id',
    #                                            suffixes=['_1', '_2'])
    #
    # df = articles_less.merge(df, left_on='_id', right_on='_id')
                                               #                                            suffixes=['_1', '_2'])
    # df = df[df['author__id_1'] < df['author__id_2']]
    # df = df[df['author__id_1'].notna() & df['author__id_2'].notna()]
    # df.drop_duplicates(inplace=True)

    # return render_template(
    #     "/graph/graph.html",
    #     elmnt_list=list(
    #         map(lambda x: {'data': {'id': x}}, (set(df.author__id_1.to_list() + df.author__id_2.to_list()))))
    #                + df[['_id', 'author__id_1', 'author__id_2']].apply(
    #         lambda row: {'data': {'id': row._id, 'source': row.author__id_1, 'target': row.author__id_2}},
    #         axis=1).to_list()
    # )
    #------------------------------------------------------------------------------
    # aa_inter = pd.read_sql_query(
    #     queries.q_cytograph5,
    #     con=db
    # )
    # df = aa_inter[['_id', 'aa']].merge(aa_inter[['_id', 'aa']], left_on='_id', right_on='_id',suffixes=['_1', '_2'])
    # df = df[df['aa_1'] < df['aa_2']]
    # df = df[df['aa_1'].notna() & df['aa_2'].notna()]
    # df.drop_duplicates(inplace=True)
    #
    # return render_template(
    #            "/graph/graph.html",
    #            elmnt_list=list(map(lambda x: {'data': {'id': x}}, (set(df.aa_1.to_list() + df.aa_2.to_list()))))
    #                       + df[['_id', 'aa_1', 'aa_2']].apply(lambda row: {'data': {'id': row._id, 'source': row.aa_1, 'target': row.aa_2}}, axis=1).to_list()
    #        )
    # ------------------------------------------------------------------------------
    db.execute(queries.q_cytograph6)
    df = pd.read_sql_query(
        queries.q_cytograph7,
        con=db
    )
    input_dir2 = r'F:\study\MADE\MADE22\project\dataset\connec_compont'
    articles_less = pd.read_csv(os.path.join(input_dir2, 'small_components_ids.csv'))
    df = articles_less.merge(df, left_on='_id', right_on='_id')
    df = df[df['aa_1'].notna() & df['aa_2'].notna()]
    df.drop_duplicates(inplace=True)

    return render_template(
        "/graph/graph.html",
        elmnt_list=list(map(lambda x: {'data': {'id': x}}, (set(df.aa_1.to_list() + df.aa_2.to_list()))))
                   + df[['_id', 'aa_1', 'aa_2']].apply(
            lambda row: {'data': {'id': row._id, 'source': row.aa_1, 'target': row.aa_2}}, axis=1).to_list()
    )

@bp.route("/ldavis")
@login_required
def ldavis():
    return render_template('vis.html')

bootstrap_for_dummies/flask_dash/templates/base.html
{% import 'util.html' as util %}
{% import 'page_wrappers.html' as wrap %}
<!DOCTYPE html>
<html lang="ru">

<head>
    {% block head %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="BS4+flask Dash based">


    <title>{%block title %} Dash and ML {% endblock%}</title>

    {% block styles %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/app.css') }}">
    {{ bootstrap.load_css() }}
    {% endblock %}

    <!-- backup bs4 from cdn -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!--font source -->
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link rel="preload" href="/static/bin/vk_sans_display_regular-webfont.woff" as="font" type="font/woff2" crossorigin="">

    {% endblock head %}
</head>

<body>
    <div class="page-wrapper chiller-theme toggled">

        <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
            <i class="fas fa-bars"></i>
        </a>
        <!--show/collapse sidebar triiger-->

        <nav id="sidebar" class="sidebar-wrapper">
            <div class="sidebar-content">
                <div class="sidebar-brand">
                    <a href="#">Menu </a>
                    <div id="close-sidebar">
                        <i class="fas fa-times"></i>
                    </div>
                </div>
                {{ util.userspace(g.user) }}
                <!--macro for userspace-->
                <!--{{ util.search_container("")}}-->
                <!-- sidebar-search  -->
                {{ util.sidebar_mainmenu()}}
                <!-- sidebar-menu  -->

            </div>
            <!-- sidebar-content  -->
            {{ util.page_footer() }}
            <!--sidebar footer-->

        </nav>
        <!-- sidebar-wrapper  -->


    <main class="page-content">
            
            <div class="container-fluid">
                <header class="flask-header">
                    {% block header %}
                     <h2> Articles Data </h2>
                     {% endblock %}
                    <hr>
                    <div class="row">
                        <div class="form-group col-md-12">
                            <!--<p> Local header</p>-->
                        </div>
                    </div>
                </header>


                <div class="flask-flash col-md-12">
                    {% for message in get_flashed_messages() %}
                        <div class="alert alert-danger">{{ message }}</div>
                    {% endfor %}
                </div>
                <!-- /flask flash-->

                <div class="form-group col-md-12">
                    {% block content %}
                    {% endblock %}
                </div>
                <!-- /content-->


                <!-- /add_content-->
            </div>

    </main>
   
    <!-- page-content" -->


    </div><!-- end .page-wrapper-->



    <!-- Optional JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
    </script>
    <script>console.log('here we are base')</script>
    <script src="{{url_for('static', filename='js/sidebar.js')}}"></script>
    <script src="{{url_for('static', filename='js/app.js')}}"></script>
    {{ bootstrap.load_js() }}
    {% block custom_scripts %}
    {% endblock %}

</body>

bootstrap_for_dummies/flask_dash/templates/base_bu.html
<!doctype html>
<html>
<head>
<title>{% block title %}{% endblock %} - Flaskr</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
<nav>
  <h1><a href="{{ url_for('index') }}">Flaskr</a></h1>
  <ul>
    {% if g.user %}
      <li><span>{{ g.user['username'] }}</span>
      <li><a href="{{ url_for('auth.logout') }}">Log Out</a>
    {% else %}
      <li><a href="{{ url_for('auth.register') }}">Register</a>
      <li><a href="{{ url_for('auth.login') }}">Log In</a>
    {% endif %}
  </ul>
</nav>

<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
</section>



<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{%block custom_scripts %}
{% endblock %}
</body>
</html>

bootstrap_for_dummies/flask_dash/templates/iframe_test.html
{% extends 'base.html' %}
{% block title %}
Dash Сводная таблица количество статей по годам.
{% endblock %}
{% block header %}
<h2>
        Dash Сводная таблица количество статей по годам.
</h2>
{% endblock %}
{% block content%}
<div>
        <iframe id="inlineFrameExample"
    title="Inline Frame Example"
    width="100%"
    height="768px"
    src="{{ url_for('/dashapp/') }}">
</iframe>
</div>
{% endblock %}

bootstrap_for_dummies/flask_dash/templates/util.html
{% macro input_text(name, value='', type='text') -%}
    <input class="flask-input" type="{{ type }}" value="{{ value|e }}" name="{{ name }}">
{%- endmacro %}

{%- macro input_textarea(name, value='', rows=10, cols=40) -%}
    <textarea class="flask-textarea"name="{{ name }}" rows="{{ rows }}" cols="{{ cols
        }}">{{ value|e }}</textarea>
{%- endmacro %}


{%- macro userspace(user) -%}

<div class="sidebar-header">
    {% if not user  %}
        <div class="user-pic">
            <img class="img-responsive img-rounded" src="{{ url_for('static', filename='/bin/anonUserPic.png') }}"
        alt="User picture">
        </div>
        <div class="user-info">
            <span class="user-name">Anonymous
            </span>
            <span class="user-role">Not logged in</span>
            <span class="user-status">
              <i class="fa fa-circle"></i>
              <span>Online</span>
            </span>
        </div>

        <div class="user-login"> <a href="{{url_for('auth.login')}}">
          <i class="fa fa-sign-in-alt" aria-hidden="true"></i>
        </a></div>
        <div class="user-login"> <a href="{{url_for('auth.register')}}">
            <i class="fas fa-angle-double-up"></i>
        </a></div>
    {% else %}
    <div class="user-pic">   
        <img class="img-responsive img-rounded" src="{{ url_for('static', filename='/bin/anonUserPic.png') }}"
        alt="User picture">
    </div>
    <div class="user-info">
      <span class="user-name"> {{ user.username | e}} </span>
      <span class="user-role"> {{ user.role }}</span>
      <span class="user-status">
        <i class="fa fa-circle"></i>
        <span> {{ user.status }}</span>
      </span>

    </div>
    <div class="user-login"> <a href="{{url_for('auth.logout')}}">
          <i class="fa fa-sign-out-alt" aria-hidden="true"></i>
        </a></div>

    {% endif %}  
</div>
  <!-- sidebar-header  -->
{%- endmacro %}

{%- macro search_container(text) -%}
<div class="sidebar-search">
    <div>
      <div class="input-group">
        {% if text == "" %}
        <input type="text" class="form-control search-menu" placeholder="Search...">
        {% else %}
        <input type="text" class="form-control search-menu" placeholder="{{ text }}">
        {% endif %}
        <div class="input-group-append">
          <span class="input-group-text">
            <i class="fa fa-search" aria-hidden="true"></i>
          </span>
        </div>
      </div>
    </div>
  </div>

<!-- search-box -->
{%- endmacro -%}


{%- macro sidebar_mainmenu(menu_items=[]) -%}
<div class="sidebar-menu">
    <ul>
      <li class="header-menu">
        <span>General</span>
      </li>
      <li class="sidebar-dropdown">
        <a href="#">
          <i class="fa fa-tachometer-alt"></i>
          <span>Dashboards</span>
        </a>
        <div class="sidebar-submenu">
          <ul>
            <li>
              <a href="{{ url_for('routes.top_authors')}}"> Top Authors
              </a>
            </li>

            <li>
              <a href="{{ url_for('routes.hello')}}"> Articles by year</a>
            </li>
            <li>
              <a href="{{url_for('routes.articles', year=2000)}}"> Aricles </a>
            </li>

          </ul>
        </div>
      </li>
      <li class="sidebar-dropdown">
        <a href="#">
          <i class="fa fa-search"></i>
          <span>Searches</span>
          <!--<span class="badge badge-pill badge-danger">3</span>-->
        </a>
        <div class="sidebar-submenu">
          <ul>
            <li>
              <a href="{{url_for('routes.search')}}">Search by topic, year, author

              </a>
            </li>
          </ul>
        </div>
      </li>

      <li class="header-menu">
        <span>Extra</span>
      </li>
      <li class="sidebar-dropdown">
        <a href="#">
          <i class="fa fa-book"></i>

          <span >Tries</span>
        </a>
        <div class="sidebar-submenu">
      <ul>
        <li>
            <a href="{{ url_for('routes.ldavis') }}">
                LDA
                </a>
        </li>
      </ul>
        </div>


  </li>
     <li>
        <a href="{{url_for('routes.cytoscape', topic='compsci')}}">
        <i class="fa fa-snowflake" aria-hidden="true"></i>
        <span> Graph </span>
        </a>
    </li>
    </ul>
  </div>
{%- endmacro -%}

{%- macro sidebar_footer(messages)-%}
<div class="sidebar-footer">
    <a href="#">  <!--TODO-->
      <i class="fa fa-bell"></i>
      <span class="badge badge-pill badge-warning notification">3</span>
    </a>
    <a href="#">
      <i class="fa fa-envelope"></i>
      <span class="badge badge-pill badge-success notification">7</span>
    </a>
    <a href="#">
      <i class="fa fa-cog"></i>
      <span class="badge-sonar"></span>
    </a>
    <a href="#">
      <i class="fa fa-power-off"></i>
    </a>
  </div>
<!--sidebar footer-->
{%  endmacro -%}


{%- macro page_footer() -%}
<footer class="text-center">
    <div class="mb-2">
        <small>
          <a href="https://data.vk.company/"><img src="/static/bin/logo_vk.svg" alt="Академия больших данных" title="Академия больших данных" style="vertical-align: middle; height: 28px;"></a>
        © 2022 <a target="_blank" rel="noopener noreferrer" href="https://data.vk.company/" style='font-family: "VK Sans Display",Arial,sans-serif;'>
          Академия больших данных

        </a>
      </small>
    </div>
    
    <div>
      <a class="footer-a" href="https://github.com/aaanX11/MADE22_project" target="_blank">
        <img class="footer-icon" src="{{ url_for('static', filename='/bin/gitlab-logo-100.png')}}" alt = "Project gitlab " /> 
          <span class="logo-text d-none d-lg-block gl-ml-3" display="inline-block">
          </span>
      </a>
    </div>
  </footer>
{%- endmacro -%}